# Generated by Django 6.0.3 on 2026-05-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppers', '0002_orderitem_status_orderitem_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
    ]
