# Generated by Django 6.0.3 on 2026-04-13 05:54

import designers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcontent',
            name='id',
            field=models.CharField(default=designers.models.generate_design_id, editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
