# Generated by Django 6.0.3 on 2026-04-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_alter_designcontent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcontent',
            name='category',
            field=models.CharField(choices=[('WOMEN', 'Women'), ('MEN', 'Men'), ('SHOES', 'Shoes'), ('BAGS', 'Bags'), ('ACCESSORIES', 'Accessories'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
