# Generated by Django 6.0.3 on 2026-05-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0003_designcontent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcontent',
            name='category',
            field=models.CharField(choices=[('WOMEN', 'Women'), ('MEN', 'Men'), ('CHILDREN', 'Children')], default='OTHER', max_length=20),
        ),
    ]
