# Generated by Django 6.0.3 on 2026-05-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0004_alter_designcontent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcontent',
            name='design_type',
            field=models.CharField(choices=[('TRADITIONAL', 'Traditional'), ('FORMAL', 'Formal'), ('CASUAL', 'Casual'), ('PARTY', 'Party'), ('SPORTS', 'Sports')], default='CASUAL', max_length=20),
        ),
    ]
